BaseURL = "http://blog.leiwang.info/"
# LanguageCode = "en-us"
Title = "Random Stuff"
# theme = "tachyons"
theme = "tailwind"
# include content marked as draft
BuildDrafts = false
# pygmentsCodeFences = true
DefaultContentLanguage = "en"

Paginate = 20

googleAnalytics = "UA-6332912-4"

[languages]
[languages.en]
title = "Random Stuff"
recentPosts = "Recent Posts"

[languages.cn]
title = "杂文"
recentPosts = "最新文章"

[params]
  Subtitle = "Some random stuff about technology and sports"
  AuthorName = "Lei"
  GitHubUser = "tendant"
  excludeTitleTypes = ["posts", "cn"]

[[menu.main]]
    name = "Home"
    title = "Home"
    weight = -110
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "中文"
    title = "中文"
    weight = -110
    identifier = "cn"
    url = "/cn"

[params.copyright]
prefix = ""
holder = "tendant"
startYear = "2015"
suffix = ""

[params.widgets]
homepage = ["recent_posts"]

[params.social]
email = "tendant@gmail.com"
github = "tendant"

[params.social.config]
platforms = ["github", "email"]

[params.recent_posts]
title = "Recent Posts"                            # default: "Recent Posts"
length = 20                            # default: 5
