baseURL = "http://blog.leiwang.info/"
languageCode = "en-us"
title = "Random Stuff"
theme = "minimo"
# include content marked as draft
buildDrafts = false
[params]
  Subtitle = "Some random thing about technology and sports"
  AuthorName = "Lei"
  GitHubUser = "tendant"

[[menu.main]]
    name = "Home"
    title = "Home"
    weight = -110
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "中文"
    title = "中文"
    weight = -110
    identifier = "cn"
    url = "/categories/中文"

[params.copyright]
prefix = ""
holder = "tendant"
startYear = "2015"
suffix = ""

# Recent Posts Widget config
[recent_posts]
title = ""                            # default: "Recent Posts"
length = 10                            # default: 5
excludeTypes = ["page"]               # default: ["page"]

[params.widgets]
homepage = ["recent_posts"]

[params.social]
email = "tendant@gmail.com"
github = "tendant"

[params.social.config]
platforms = ["github", "email"]
