baseURL = "http://blog.leiwang.info/"
languageCode = "en-us"
title = "Random Stuff"
theme = "minimo"
# include content marked as draft
buildDrafts = false
[params]
  Subtitle = "Some random thing about technology and sports"
  AuthorName = "Lei"
  GitHubUser = "tendant"

[params.copyright]
prefix = ""
holder = "tendant"
startYear = "2018"
suffix = ""

[params.widgets]
homepage = ["recent_posts"]

[params.social]
email = "tendant@gmail.com"
github = "tendant"
twitter = "tendant"

[params.social.config]
platforms = ["github", "twitter", "email"]

