# Base URL of the site, the only required config argument
base_url = "http://blog.leiwang.info/"
# base_url = "localhost"

theme = "stuff"

taxonomies = [
  { name = "tags" },
  { name = "categories", paginate_by = 10},
  { name = "tags", lang = "cn"},
  { name = "categories", lang = "cn"}
]

languages = [
  { code = "cn" }
]

[extra]
author = "Lei"

[[extra.navs]]
  name = "Home"
  title = "Home"
  weight = -110
  identifier = "home"
  lang = "en"
  url = "/"

[[extra.navs]]
  name = "中文"
  title = "中文"
  weight = -110
  identifier = "cn"
  lang = "cn"
  url = "/cn"
