baseURL = "http://blog.leiwang.info/"
languageCode = "en-us"
title = "Random Stuff"
theme = "minimo"
# include content marked as draft
buildDrafts = false
[params]
  Subtitle = "Some random thing about technology and sports"
  AuthorName = "Lei"
  GitHubUser = "tendant"